
 
prometheus_endpoint: 'http://192.168.154.97:9090'
prometheus_config_template: '/root/original_prometheus_config.yaml'
prometheus_config_target: '/root/prometheus_config.yaml'
prometheus_rules_directory: '/var/lib/micado/prometheus/config'

swarm_endpoint: 'http://192.168.154.97:2375'
occopus_endpoint: 'http://localhost:5000'
occopus_infra_name: 'micado_worker_infra'
occopus_worker_name: 'worker'

logging:
    version: 1
    root:
        level: INFO
        handlers: [console, file]
    formatters:
        simpleFormatter:
            #format: "%(module)s %(asctime)s %(levelname)s %(message)s"
            format: "%(asctime)s %(levelname)s %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormatter
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: pk.log
    loggers:
        pk:
            propagate: false
            handlers: [console, file]
        pk_k8s:
            propagate: false
            handlers: [console, file]
        pk_prometheus:
            propagate: false
            handlers: [console, file]


